# Generated by Django 5.2.8 on 2026-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('order_rate_editable', models.BooleanField(default=False)),
                ('default_price_codes', models.JSONField(default=list)),
                ('protected_price_categories', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'settings_options',
            },
        ),
    ]
