# Generated by Django 5.2.8 on 2026-01-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_options', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsoptions',
            name='default_price_codes',
        ),
        migrations.RemoveField(
            model_name='settingsoptions',
            name='protected_price_categories',
        ),
        migrations.AddField(
            model_name='settingsoptions',
            name='default_price_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settingsoptions',
            name='protected_price_users',
            field=models.JSONField(default=dict),
        ),
    ]
