# Generated by Django 5.0.2 on 2025-11-04 06:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0007_userareas_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchin',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
