# Generated by Django 5.0.2 on 2025-11-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0008_alter_punchin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchin',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='punchin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='punch_images/%Y/%m/%d/'),
        ),
    ]
