# Generated by Django 5.2.8 on 2026-01-13 05:18

import PunchIn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0009_remove_punchin_photo_url_punchin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=PunchIn.models.punchin_photo_path),
        ),
    ]
