# Generated by Django 5.2.8 on 2025-12-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_accinvmast_accledgers_accmaster_cashandbankaccmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccPriceCode',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_pricecode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccProduct',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('taxcode', models.CharField(blank=True, max_length=10, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('defected', models.CharField(blank=True, max_length=5, null=True)),
                ('text6', models.CharField(blank=True, max_length=200, null=True)),
                ('settings', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('secondprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('thirdprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fourthprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('nlc1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('bmrp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('modifiedtime', models.TimeField(blank=True, null=True)),
                ('settings', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_productbatch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_departments',
            },
        ),
        migrations.CreateModel(
            name='AccGoddown',
            fields=[
                ('goddownid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_goddown',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccGoddownStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goddownid', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('barcode', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_goddownstock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccSalesTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('goddown', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_sales_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccProductPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_productphoto',
                'managed': True,
                'indexes': [models.Index(fields=['code', 'client_id'], name='acc_product_code_214f11_idx')],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'collection',
                'managed': True,
                'indexes': [models.Index(fields=['client_id'], name='collection_client__cf916f_idx')],
            },
        ),
    ]
