# Generated by Django 5.2.8 on 2026-01-13 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_accpricecode_accproduct_accproductbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_code', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('item_code', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('uploaded to server', 'Uploaded to Server'), ('completed', 'Completed')], default='uploaded to server', max_length=30)),
                ('status_changed_date', models.DateField(blank=True, null=True)),
                ('status_changed_time', models.TimeField(blank=True, null=True)),
                ('status_changed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item_orders',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='collection_client__cf916f_idx',
        ),
        migrations.AddField(
            model_name='collection',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('uploaded to server', 'Uploaded to Server'), ('completed', 'Completed')], default='uploaded to server', max_length=30),
        ),
        migrations.AddField(
            model_name='collection',
            name='uploaded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='uploaded_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='uploaded_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
